### ISSUE TITLE
Request: Conda package

### ISSUE THREAD

**Issue by hochshi** [neilswainston/synbiochem-py#2]
Hi,

Could you please publish a conda package? (I think conda-forge has an easy to follow how to)
I'm building a tool which depends on your package and would like to distribute it through conda.

**Comment by neilswainston** [comment]
Hi there,

Thanks for the suggestion. Unfortunately, though, the synbiochem-py package is no longer being actively maintained.

However, with conda, you should still be able to install it through pip. Alternatively, please consider forking the project and implementing conda support.

Best wishes,

Neil.

Neil Swainston, PhD

Institute of Integrative Biology
University of Liverpool
Liverpool L69 7ZB
United Kingdom

On 12 Mar 2020, at 08:19, hochshi <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi,

Could you please publish a conda package? (I think conda-forge has an easy to follow how to)
I'm building a tool which depends on your package and would like to distribute it through conda.

**Comment by hochshi** [comment]
Ok.
Thank you
