### ISSUE TITLE
requests ssl SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by Melclic** [neilswainston/synbiochem-py#3]
I have been having issues with SSL handshake failures (in PartsGenie actually)  that calls functions from this package:

`synbiochem.utils.seq_utils import get_uniprot_values
`
`
uniprot_vals = get_uniprot_values(['P31013'], ['sequence'])
`

Causes:

`
HTTPSConnectionPool(host='www.uniprot.org', port=443): Max retries exceeded with url: /uniprot/?query=id:P31013&format=tab&columns=id,sequence (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1076)')))
`

This is fixed by downgrading the python requests package to the UniProt specified version (https://www.ebi.ac.uk/training/online/sites/ebi.ac.uk.training.online/files/UniProt_programmatically_py3.pdf)

`
requests==2.12.4
`

Cheers

**Comment by neilswainston** [comment]
Fixed. Thanks!
